### ISSUE TITLE
App closed after installation on android device

### ISSUE THREAD

**Issue by gbaski** [espresso3389/flutter_rtmp_publisher#1]
Every attempt to open the example-snippet after installation, close back instantly.

I got this response from android studio

D/EGL_emulation( 7422): eglMakeCurrent: 0xaa1052a0: ver 2 0 (tinfo 0xaa103220)
I/RtmpPublisherWrapper( 7422): onCameraSizeDetermined: 480, 640
D/        ( 7422): HostConnection::get() New Host Connection established 0x86e7bcc0, tid 7561
D/EGL_emulation( 7422): eglCreateContext: 0x86e5f620: maj 2 min 0 rcv 2
D/EGL_emulation( 7422): eglMakeCurrent: 0x86e5f620: ver 2 0 (tinfo 0x86ddc0b0)
E/libc    ( 7422): Access denied finding property "ro.opengles.version"
I/flutter ( 7422): cameraSize: 480 x 640
W/jp.espresso3389.flutter_rtmp_publisher_example( 7422): type=1400 audit(0.0:60): avc: denied { read } for comm=474C5468726561642031313839 name="u:object_r:opengles_prop:s0" dev="tmpfs" ino=3999 scontext=u:r:untrusted_app:s0:c512,c768 tcontext=u:object_r:opengles_prop:s0 tclass=file permissive=0
D/Grafika ( 7422): Created program 3 (TEXTURE_EXT)
E/EGL_emulation( 7422): eglQueryContext 32c0  EGL_BAD_ATTRIBUTE
E/EGL_emulation( 7422): tid 7561: eglQueryContext(1804): error 0x3004 (EGL_BAD_ATTRIBUTE)
D/        ( 7422): HostConnection::get() New Host Connection established 0x8acaeec0, tid 7434
I/Choreographer( 7422): Skipped 33 frames!  The application may be doing too much work on its main thread.
D/        ( 7422): HostConnection::get() New Host Connection established 0x86e7bec0, tid 7541
D/        ( 7422): HostConnection::get() New Host Connection established 0x86e7be80, tid 7436
D/        ( 7422): HostConnection::get() New Host Connection established 0x8acb8a40, tid 7580

**Comment by espresso3389** [comment]
Do you using Android Emulator?
I did check with certain real devices only...

**Comment by gbaski** [comment]
I installed it on a real device, closes after launch

**Comment by espresso3389** [comment]
> I installed it on a real device, closes after launch

I'm just curious why there are only EGL_emulation and no real EGL device logs...
Could you show me what device(s) are you using?

**Comment by gbaski** [comment]
Another issue, when i run `flutter build apk`, i was asked to upgrade gradle to 5.1.1, 
Now i got the below response

Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by gbaski** [comment]
After some random testings, `app-debug.apk` was my claim that it crashed , not the case for `app-release.apk`

**Comment by gbaski** [comment]
Thanks, it's working, tested playback with VLC player. One more thing, how do i go about playback for stream subscribers?

**Comment by espresso3389** [comment]
Do you mean RTMP player? If so, I don't know about RTMP player.

But normally RTMP stream is relayed by HLS server and HLS stream can be received using Flutter's official [video_player](https://pub.dev/packages/video_player).

**Comment by gbaski** [comment]
Alright, Thanks.

**Comment by gbaski** [comment]
In my use-case, HLS playback could hinder the business objective because of it high latency, 30 to 45 seconds is a bad user experience for an interactive live broadcasting solution.

This package, it parent native android RTMP library has RTMP player repository. I want to ask if technically possible to create flutter-dart plugin for the RTMP player.

**Comment by gbaski** [comment]
Thanks for your support, found this player https://github.com/CaiJingLong/flutter_ijkplayer perfect for RTMP.
